-- 코드를 입력하세요
SELECT YEAR, MONTH, COUNT(*) AS PUCHASED_USERS,
    ROUND((COUNT(*) / (SELECT COUNT(*)
                      FROM USER_INFO WHERE YEAR(JOINED) = 2021)), 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.USER_ID
    FROM ONLINE_SALE AS A
    JOIN USER_INFO AS B ON A.USER_ID = B.USER_ID AND YEAR(JOINED) = 2021
) AS C
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;