-- 코드를 입력하세요
SELECT C.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW AS A
JOIN (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC LIMIT 1
) AS B ON A.MEMBER_ID = B.MEMBER_ID
JOIN MEMBER_PROFILE AS C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;