-- 코드를 입력하세요
SELECT PRODUCT_CODE, (B.SALES_AMOUNT*A.PRICE) AS SALES
FROM PRODUCT AS A 
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ;